adb shell pm install-existing --user 0 com.glance.internet
adb shell pm install-existing --user 0 com.heytap.pictorial
adb shell pm install-existing --user 0 com.opos.cs
adb shell pm install-existing --user 0 com.coloros.weather2
adb shell pm install-existing --user 0 com.redteamobile.roaming
adb shell pm install-existing --user 0 com.google.android.apps.nbu.paisa.user
adb shell pm install-existing --user 0 com.google.android.apps.googleassistant
adb shell pm install-existing --user 0 com.google.android.youtube
adb shell pm install-existing --user 0 com.google.android.apps.nbu.files
adb shell pm install-existing --user 0 com.google.android.dialer
adb shell pm install-existing --user 0 com.google.android.contacts
adb shell pm install-existing --user 0 com.coloros.securepay
adb shell pm install-existing --user 0 com.coloros.video
adb shell pm install-existing --user 0 com.heytap.yoli
adb shell pm install-existing --user 0 com.heytap.music
adb shell pm install-existing --user 0 com.finshell.fin
adb shell pm install-existing --user 0 com.finshell.wallet
adb shell pm install-existing --user 0 com.heytap.browser
adb shell pm install-existing --user 0 com.google.android.apps.messaging
adb shell pm install-existing --user 0 com.facebook.appmanager
adb shell pm install-existing --user 0 com.facebook.system
adb shell pm install-existing --user 0 com.facebook.services
adb shell pm install-existing --user 0 com.heytap.speechassist
adb shell pm install-existing --user 0 com.heytap.cloud
adb shell pm install-existing --user 0 com.coloros.familyguard
adb shell pm install-existing --user 0 com.google.android.apps.podcasts
adb shell pm install-existing --user 0 com.google.android.apps.youtube.music
adb shell pm install-existing --user 0 com.google.android.videos
adb shell pm install-existing --user 0 com.google.android.apps.magazines
adb shell pm install-existing --user 0 com.google.android.apps.tachyon
adb shell pm install-existing --user 0 com.google.android.apps.subscriptions.red
adb shell pm install-existing --user 0 com.os.docvault
adb shell pm install-existing --user 0 com.coloros.backuprestore
adb shell pm install-existing --user 0 com.heytap.xgame
adb shell pm install-existing --user 0 com.oplus.play
adb shell pm install-existing --user 0 com.realme.link
adb shell pm install-existing --user 0 com.coloros.onekeylockscreen
adb shell pm install-existing --user 0 com.heytap.smarthome
adb shell pm install-existing --user 0 com.coloros.shortcuts
adb shell pm install-existing --user 0 com.oplus.games
adb shell pm install-existing --user 0 com.android.email
adb shell pm install-existing --user 0 com.coloros.assistantscreen
adb shell pm install-existing --user 0 com.nearme.instant.platform
adb shell pm install-existing --user 0 com.heytap.accessory
adb shell pm install-existing --user 0 com.heytap.htms
adb shell pm install-existing --user 0 com.heytap.usercenter
adb shell pm install-existing --user 0 com.coloros.findphone.client2
adb shell pm install-existing --user 0 com.coloros.findmyphone
adb shell pm install-existing --user 0 com.oplus.cosa
adb shell pm install-existing --user 0 com.iflytek.speechsuite
adb shell pm install-existing --user 0 com.coloros.ocrscanner
adb shell pm install-existing --user 0 com.coloros.colordirectservice
adb shell pm install-existing --user 0 com.oplus.ovoicemanager.wakeup
adb shell pm install-existing --user 0 com.oppo.ovoicemanager
adb shell pm enable --user 0 com.heytap.market

pause
